sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 663592
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx08beb71379ccdc26
    secret: 4e4c6fdefc405305beabb134c77bbb3d